#!/bin/bash

pip install -r requirements.txt
pip install -e .  # installs the 'psh' package in editable mode

printf '#!/bin/bash'"\nexport PYTHONPATH="`pwd`":\$PYTHONPATH\npython3 -m psh.run" > psh/psh

chmod a+x ./psh/psh

sudo cp ./psh/psh /usr/local/sbin/psh

printf '#!/bin/bash'"\nexport PYTHONPATH="`pwd`":\$PYTHONPATH\npython3 -m psh.run -s < \"\$@\"" > psh/pshs

chmod a+x ./psh/pshs

sudo cp ./psh/pshs /usr/local/sbin/pshs
